name: Test OIDC upload

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: XDanielPaul/upload-components-ci-action@fix/do_not_require_api_token_with_dry_run
        with:
          components: "banana: ./cmp_ex"
          version: "3.3.14"
          namespace: "xdanielpaul"
          dry_run: true
