name: Test OIDC upload

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: XDanielPaul/upload-components-ci-action@v2
        with:
          components: "banana: ./cmp_ex"
          version: "3.3.14"
          namespace: "xdanielpaul"
          api-token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          dry-run: true
