name: Test OIDC

on:
  workflow_dispatch:

jobs:
  check-oidc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Request OIDC Token
        id: get_token
        run: |
          token=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                        "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=localhost:5000" | jq -r .value)
          echo "OIDC_TOKEN=$token" >> $GITHUB_ENV
          echo "Token: $token"

      - name: Send OIDC Token to Local Service
        run: |
          curl -X POST "https://random-subdomain.ngrok.io/auth" \
               -H "Content-Type: application/json" \
               -d '{"token": "'"${{ env.OIDC_TOKEN }}"'"}'
