name: Test OIDC upload

on:
  workflow_dispatch:

jobs:
  upload_components:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: XDanielPaul/upload-components-ci-action@v2
        with:
          components: "cmp: ./cmp_ex"
          version: "1.0.2"
          namespace: "XDanielPaul"
          registry_url: "https://104d-195-122-199-236.ngrok-free.app"
